// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make mocks`.

package mocks

import marketplace "github.com/ilgooz/mattermost-plugin-marketplace-addon/server/marketplace"
import mock "github.com/stretchr/testify/mock"

// Marketplace is an autogenerated mock type for the Marketplace type
type Marketplace struct {
	mock.Mock
}

// ListPlugins provides a mock function with given fields:
func (_m *Marketplace) ListPlugins() (marketplace.Plugins, error) {
	ret := _m.Called()

	var r0 marketplace.Plugins
	if rf, ok := ret.Get(0).(func() marketplace.Plugins); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(marketplace.Plugins)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
